# Install helper for Kritical.Lens.SchemaCompleteness
# Auto-generated by scripts/tools/Apply-KriticalLensRetrofits.mjs (.5180+)
[CmdletBinding()]
param(
    [switch]$Force,
    [ValidateSet('CurrentUser','AllUsers')]
    [string]$Scope = 'CurrentUser'
)
$ErrorActionPreference = 'Stop'

Write-Host 'Kritical.Lens.SchemaCompleteness install' -ForegroundColor Cyan

# 1. Ensure Krit.OmniFramework is available (soft dep).
if (-not (Get-Module -Name 'Krit.OmniFramework' -ListAvailable -ErrorAction SilentlyContinue)) {
    Write-Host '  installing Krit.OmniFramework...' -ForegroundColor Yellow
    Install-Module -Name 'Krit.OmniFramework' -Scope $Scope -Force:$Force -ErrorAction Stop
}

# 2. Import THIS module via its psd1.
$manifest = Join-Path $PSScriptRoot 'src' 'Kritical.Lens.SchemaCompleteness.psd1'
if (-not (Test-Path -LiteralPath $manifest)) {
    throw "Manifest not found: $manifest"
}
Import-Module $manifest -Force -ErrorAction Stop

# 3. Register with the Lens Emitter Registry when available.
if (Get-Command Register-KriticalLensEmitter -ErrorAction SilentlyContinue) {
    $metaPath = Join-Path $PSScriptRoot 'src' 'meta.json'
    if (Test-Path -LiteralPath $metaPath) {
        $meta = Get-Content -LiteralPath $metaPath -Raw | ConvertFrom-Json
        Register-KriticalLensEmitter -Meta $meta
        Write-Host "  registered with Kritical.Lens.Core.EmitterRegistry" -ForegroundColor Green
    }
}

Write-Host 'Kritical.Lens.SchemaCompleteness install complete' -ForegroundColor Green
