# Pester smoke test for Kritical.Lens.SchemaCompleteness
# Auto-generated by scripts/tools/Apply-KriticalLensRetrofits.mjs (.5180+)
# Anchor: WORKING-SUPERVISOR-.5178-post-overnight-6-waves-shipped-20260703T221416Z
# This is a MINIMUM smoke test. Extend it with real behaviour asserts.

BeforeAll {
    $manifestPath = Join-Path $PSScriptRoot '..' 'src' 'Kritical.Lens.SchemaCompleteness.psd1'
    if (Test-Path -LiteralPath $manifestPath) {
        Import-Module $manifestPath -Force -ErrorAction Stop
    }
}

Describe 'Kritical.Lens.SchemaCompleteness — module smoke' {
    It 'has a valid psd1 manifest' {
        $manifestPath = Join-Path $PSScriptRoot '..' 'src' 'Kritical.Lens.SchemaCompleteness.psd1'
        Test-Path -LiteralPath $manifestPath | Should -BeTrue
        $m = Test-ModuleManifest -Path $manifestPath -ErrorAction SilentlyContinue
        $m | Should -Not -BeNullOrEmpty
    }

    It 'has non-empty exported functions (or documents why)' {
        $manifestPath = Join-Path $PSScriptRoot '..' 'src' 'Kritical.Lens.SchemaCompleteness.psd1'
        $m = Test-ModuleManifest -Path $manifestPath -ErrorAction SilentlyContinue
        # Not enforced as FAIL — some submodules may deliberately export none
        # until sub-features stabilise. Documented in README.md when so.
        $m.ExportedFunctions.Count | Should -BeGreaterOrEqual 0
    }

    It 'ships a meta.json matching the Emitter Registration Contract' {
        $metaPath = Join-Path $PSScriptRoot '..' 'src' 'meta.json'
        if (-not (Test-Path -LiteralPath $metaPath)) {
            $metaPath = Join-Path $PSScriptRoot '..' 'meta.json'
        }
        Test-Path -LiteralPath $metaPath | Should -BeTrue
        $meta = Get-Content -LiteralPath $metaPath -Raw | ConvertFrom-Json
        $meta.name | Should -Be 'Kritical.Lens.SchemaCompleteness'
        $meta.category | Should -Not -BeNullOrEmpty
        $meta.purpose | Should -Not -BeNullOrEmpty
        $meta.audits.Count | Should -BeGreaterThan 0
    }
}
